### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by sghoe** [adsau59/fishyboteso#7]
Traceback (most recent call last):
  File "fishy.py", line 1, in <module>
    from pixel_loc import *
  File "E:\master\pixel_loc.py", line 1, in <module>
    from fishing_event import *
  File "E:\master\fishing_event.py", line 1, in <module>
    from fishing_mode import *
  File "E:\master\fishing_mode.py", line 1, in <module>
    from window import *
  File "E:\master\window.py", line 1, in <module>
    from log import *
  File "E:\master\log.py", line 1, in <module>
    from controls import *
  File "E:\master\controls.py", line 1, in <module>
    from init import *
  File "E:\master\init.py", line 29, in <module>
    import imutils as imutils
  File "C:\Users\sh\AppData\Local\Programs\Python\Python37-32\lib\site-packages\imutils\__init__.py", line 8, in <module>
    from .convenience import translate
  File "C:\Users\ah\AppData\Local\Programs\Python\Python37-32\lib\site-packages\imutils\convenience.py", line 6, in <module>
    import cv2
  File "C:\Users\ah\AppData\Local\Programs\Python\Python37-32\lib\site-packages\cv2\__init__.py", line 3, in <module>
    from .cv2 import *
ImportError: DLL load failed: Das angegebene Modul wurde nicht gefunden.

**Comment by sghoe** [comment]
Any ideas?

**Comment by adsau59** [comment]
looks like modules haven't installed correctly... try installing them again

**Comment by adsau59** [comment]
okay, it has been a long time since u haven't respond... im closing this issue for now, if u encounter this problem again, feel free to reopen it or create a new issue :)
